"""Canonical Korean property names for the two Notion data sources."""

ROLE_NAME = "직무명"
ROLE_CATEGORY = "직무 분야"
ROLE_STATUS = "상태"
ROLE_EXPERIENCE_LEVEL = "경력 수준"
ROLE_DESCRIPTION = "직무 설명"
ROLE_KEY_RESPONSIBILITIES = "주요 업무"
ROLE_FIRST_DISCOVERED = "최초 발견일"
ROLE_LAST_REVIEWED = "최근 검토일"
ROLE_EVIDENCE_SOURCES = "근거 출처"
ROLE_NOTES = "메모"

TREND_TITLE = "제목"
TREND_SUMMARY = "요약"
TREND_KEY_INSIGHT = "핵심 시사점"
TREND_SOURCE_TYPE = "출처 유형"
TREND_SOURCE_NAME = "출처명"
TREND_ORIGINAL_URL = "원문 URL"
TREND_PUBLISHED_DATE = "게시일"
TREND_COLLECTED_DATE = "수집일"
TREND_RELATED_ROLES = "관련 직무"
TREND_DOMAIN = "관련 분야"
